### ISSUE TITLE
Change hash path to /_fos_user_context_hash

### ISSUE THREAD

**Issue by ddeboer** [FriendsOfSymfony/FOSHttpCacheBundle#212]
See https://github.com/FriendsOfSymfony/FOSHttpCache/issues/165 and https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/issues/189#issuecomment-73405192.

**Comment by dbu** [comment]
is this not done in #201 ? what is missing?

**Comment by dbu** [comment]
hm, can it be that readthedocs stopped building the doc? http://foshttpcachebundle.readthedocs.org/en/latest/reference/configuration/user-context.html#context-hash-route is indeed outdated. can we somehow see that inside their system? or trigger a rebuild manually?

**Comment by ddeboer** [comment]
Ah, that’s the problem. I saw the old hash URL in our docs, so I assumed that we forgot to change it. The docs are failing with:

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/foshttpcachebundle/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/foshttpcachebundle/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 143, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/foshttpcachebundle/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 433, in setup_extension
    err)
ExtensionError: Could not import extension sensio.sphinx.configurationblock (exception: No module named sensio.sphinx.configurationblock)

Extension error:
Could not import extension sensio.sphinx.configurationblock (exception: No module named sensio.sphinx.configurationblock)
```

I added my e-mail address to the notifications so we find out sooner about issues like this.

**Comment by ddeboer** [comment]
> can we somehow see that inside their system? or trigger a rebuild manually?

If you log in on readthedocs.org, you should be able to access the FOSHttp projects. 

Fixed by building enabling virtualenv in the RTD build config.
